### ISSUE TITLE
Upload the PSU demo to the heroku account

### ISSUE THREAD

**Issue by hdoma** [codeforpdx/open-data-streams#20]
Let's upload the demo to the Heroku account

**Comment by hdoma** [comment]
Need to respond to CfA for the heroku account

**Comment by timeonator** [comment]
The app is ready to deploy functionally. It'll be a baseline in terms of functionality. I may have to rename the app, per the deployment instructions from Cecilia, which will trigger another build and test cycle. 

I sent Cecilia a note about the schedule. I plan on starting the deployment this week. 

I had to fix some deprecated issues around static files and move passwords and the secret key out of the source code to prepare for deployment.

**Comment by timeonator** [comment]
It's been running on heroku for a least a month now so, closing
